[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["multipart"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls", "postgres", "chrono" ] }
rumqttc = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonwebtoken = "9"
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
anyhow = "1"
sha2 = "0.11.0"
pgvector = { version = "^0.3", features = ["sqlx"] }
tower-http = { version = "^0.5", features = ["cors"] }
base64 = "0.22"
ort = { version = "2.0.0-rc.9", features = ["ndarray"] }
image = "0.24"
ndarray = "0.17"
